%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%-Opening of .dat file
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
function [Problem_Type,Geom_Name]=Intro
one='____________________________________________________________________';
two='====================================================================';
fprintf('%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n%s\n', ...
        two,...
        '2D Linear Problems.', ...
        two,...
        'Select the Problem Type.', ...
        '1. Eigenfrequency extraction Analysis.', ...
        '2. Static Analysis.', ...
        two);
%Problem_Type=input('Select the Problem Type. Type = ');
Problem_Type=2
fprintf('%s\n%s\n', ...
        two,...
        'Geometry Information:');
%
%Geom_Name=zeros(Patch_Num);
%Geom_Name=sym(Geom_Name);
%for i=1:Patch_Num
prompt = 'Name of the Geometry file (name.dat) = ';
Geom_Name=input(prompt,'s');
%end
%
fprintf('%s\n', ...
        two);
%---end of function
end